layout_spectrum: 0
typography_spectrum: 0.2132616
color:
  saturation: 1
  lightness: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Be
